### ISSUE TITLE
'RNSimpleToastSpec.h' file not found

### ISSUE THREAD

**Issue by fire-blaster** [vonovak/react-native-simple-toast#29] opened 2022-12-15 13:03 UTC
'RNSimpleToastSpec.h' file not found error occurs while i'm trying to build archive file at iOS side 
![image](https://user-images.githubusercontent.com/56085002/207865824-954a059c-dba5-4b96-a292-b5b7a1bf7688.png)

**Comment by vonovak** [comment] 2022-12-15 14:34
Hello and thanks for reporting,
this seems like a duplicate of #27

if not, please open a new issue and include a https://stackoverflow.com/help/minimal-reproducible-example
Thank you 🙂

**Closed as completed by vonovak** 2022-12-15 14:34 UTC

**Comment by fire-blaster** [comment] 2022-12-15 17:03
> Hello and thanks for reporting, this seems like a duplicate of #27
> 
> if not, please open a new issue and include a https://stackoverflow.com/help/minimal-reproducible-example Thank you 🙂

Thanks for your response
I am not using react-native-firebase although I should include that package?

**Comment by vonovak** [comment] 2022-12-16 07:50
Hello, no, react-native-firebase is not related. I didn't say anything about it.. 🤔 ?

**Comment by shoaibarifArgonTech** [comment] 2023-06-07 13:59
Any solution?
